### ISSUE TITLE
Spanish language support

### ISSUE THREAD

**Issue by MiClobiMC** [pop123123123/sentence-mixing#1]
Is it possible to do a tutorial how to install? Does it work in Spanish?

**Comment by nbusser** [comment]
Hi, this project is only a library.  
You can find applications here:
* [CLI application](https://github.com/pop123123123/CLI_sentence_mixing)
* [GUI application (unstable)](https://github.com/pop123123123/SentenceMixingMaker)

Soon, we will write documentation for these applications and make GUI stable.

Unfortunately, only french language is supported right now. When the GUI application will be stable, we will think about extend the library to other languages. It seems not so complicated to do regarding our architecture.

**Comment by pop123123123** [comment]
If you want to try in your language though, when you install Montreal Forced Aligner just follow the instructions and take Spanish acoustic and pronunciation models, instead of french ones as indicated on this repo, this should work out of the box.

**Comment by nbusser** [comment]
Hi @MiClobiMC  !

Yesterday, we added language support to the library.

Sadly, the only pre-made dictionaries we could find were in English and in German.

However, it exists a [Spanish pretrained model](https://github.com/MontrealCorpusTools/mfa-models/raw/master/acoustic/spanish.zip) for MFA. The only thing lacking is the **pronunciation dictionary**, decomposing each word of the language to phonemes.

We wrote a [guide to add an unsupported language](https://github.com/pop123123123/sentence-mixing#add-an-unsupported-language). We have no real clue of how long, how tedious and how difficult it is to create such dictionary. Hopefully, the task is pretty easy.

You should definitely ask [Michael McAuliffe](https://github.com/mmcauliffe) about this. I'm sure that he will guide you in such task. Contact him at michael.e.mcauliffe@gmail.com.

If you want to add support for Spanish language, please keep us in touch.

**Comment by MiClobiMC** [comment]
Hello, I just saw the tutorial, the installation went very well but it only works in English since I tested in Spanish and since there is no dictionary in Spanish it gives an error

**Comment by nbusser** [comment]
You should then contact Michael McAuliffe and ask him for Spanish dictionary creation guideline.

**Comment by MiClobiMC** [comment]
Does the IPA dictionary work? https://raw.githubusercontent.com/kylebgorman/wikipron/master/data/scrape/tsv/spa_latn_la_phonemic_filtered.tsv

**Comment by MiClobiMC** [comment]
I have spoken with Michael but he tells me that I have to generate the dictionary but the problem is that I have windows and I cannot do it

**Comment by nbusser** [comment]
Can you tell us more about what Michael actually said about _generating the dictionary_ ?  
We guess that Michael told you to use g2p to generate your dictionary.  

### Workaround

Here is the error you likely get when trying to give the IPA spanish dict to the  [GlobalPhone MFA spanish model](https://github.com/MontrealCorpusTools/mfa-models/raw/master/acoustic/spanish.zip):
```
dictionary phones: {'k', 'd', 'a', 's', 'f', 'm', 'i', 't', 'n', 'b', 'ɲ', 'p', 'j', 'ɾ', 'l', 'ɡ', 't͡ʃ', 'r', 'u', 'o', 'ɟ͡ʝ', 'e', 'x', 'w'}
model phones: {'i+', 'd', 'k', 'a', 'a+', 's', 'aI', 'f', 'u+', 'm', 'i', 'L', 't', 'z', 'tS', 'n~', 'e+', 'n', 'b', 'p', 'G', 'j', 'g', 'l', 'ng', 'o+', 'V', 'r', 'rf', 'eU', 'u', 'o', 'aU', 'oI', 'e', 'D', 'T', 'x', 'eI', 'w'}
```
You see that the phonemes symbols of the dictionary (```dictionary_phones```) are different from the phonemes symbols whose the MFA model have been trained with (```model_phones```).   

Four phonemes ```ɲ```, ```ɾ```, ```t͡ʃ``` and ```ɟ͡ʝ``` appear in the IPA dictionary but are not known by the MFA model.  
You then only need to replace these four phonemes with their MFA equivalent everytime they appear on the dictionary.

#### Warning
The IPA dictionary you find looks great.  
However, you can see that it uses only 24 phonemes while MFA is trained with 40 phonemes.  
It means that if you change the phonemes of the IPA dictionary to match the phonemes of the MFA model, you could loose a lot of precision. 

**Please give us the process that Michael told you, so we can think about this (we will probably change our architecture if there is a way to turn it more dynamic).**

**Comment by MiClobiMC** [comment]
![estoes](https://user-images.githubusercontent.com/60762569/114441811-d6bdda00-9b99-11eb-9214-912da7657308.JPG)

**Comment by nbusser** [comment]
We will likely change the library and use dynamic g2p generated dictionaries instead of static dictionaries.  
Regarding our current investment on the project, it will probably take **more than a month.**

Waiting for that modification, you should use the workaround I specified in my previous message. It should be simple and fast to do. Tell us if you have any question or if you encounter difficulties.

**Comment by MiClobiMC** [comment]
I did the above to replace phonemes but I don't have the consonants and vowels in Spanish

**Comment by nbusser** [comment]
You have to create this small dict.  
It's very simple:
- put the vowel phonemes in the line VOWEL
- put the consonant phonemes in the line CONSONANT
- add the line ```SPACE sp```

Here is an [example](https://github.com/nbusser/SM-Dictionaries/blob/master/fr/fr_consonant_vowel.dict)

**Comment by MiClobiMC** [comment]
I have a doubt ɟ͡ʝ which phoneme does it belong to in the mfa model

**Comment by nbusser** [comment]
It looks like a vowel.

**Comment by MiClobiMC** [comment]
I did the phonemes replacement, but I still have this problem:
![fatalerror](https://user-images.githubusercontent.com/60762569/114616955-80be6480-9c75-11eb-9f7d-584954bfb644.JPG)

**Comment by nbusser** [comment]
Did you use the same dictionary ?
It says that the phonemes ```N```, ```Z``` for example are in your dictionary but I cannot find them when browsing it.  
Can you explain me what you did when replacing the phonemes ?

**Comment by MiClobiMC** [comment]
Well, the phonemes that you told me to replace, I replaced them with the notepad example ɲ = N ɾ = D t͡ʃ = J ɟ͡ʝ = Y
![consonantes](https://user-images.githubusercontent.com/60762569/114624455-b7e54380-9c7e-11eb-9352-b3762b78a0da.JPG)

![asi](https://user-images.githubusercontent.com/60762569/114624533-dba88980-9c7e-11eb-9e0d-f1cf1f3bf36a.JPG)

**Comment by MiClobiMC** [comment]
![asi](https://user-images.githubusercontent.com/60762569/114624533-dba88980-9c7e-11eb-9e0d-f1cf1f3bf36a.JPG)

**Comment by nbusser** [comment]
Ok you drove the correct process.  
  
However, you did some mistakes: you can see in the list of the model phonemes in my [previous post](https://github.com/pop123123123/sentence-mixing/issues/1#issuecomment-817660903) that, for example, phoneme ```N``` does not exist (while phoneme ```n``` does).

It looks like you inserted as well other undefined phonemes like ```Z``` or ```β```.

Make sure that ```dictionary phones``` is a subset of ```model phones``` in the error message.

**Comment by MiClobiMC** [comment]
aligner.exceptions.PronunciationAcousticMismatchError: There were phones in the dictionary that do not have acoustic models: ɡ I already fixed the others but I still have that one that is an invalid character but it appears as g
![erroracustic](https://user-images.githubusercontent.com/60762569/114626965-75be0100-9c82-11eb-9226-2da30a1b4911.JPG)

**Comment by MiClobiMC** [comment]
It says the word was not recognized, while the word is in the video and in the dictionary
![fixbut](https://user-images.githubusercontent.com/60762569/114627689-ab171e80-9c83-11eb-82c4-8cfd597b0c24.JPG)

**Comment by nbusser** [comment]
The program doesn't find *HOLA* in the dictionary. Are you sure you correctly changed the ```config.json``` ?  
A good thing you can try is to **delete** ```.downloads``` and ```.subs``` folders and ```save.pckl``` file.

Since your initial problem is solved, we will close this issue.

If you got further issues related to the usage of the CLI application, I suggest you to look for its reference in the [restrictions/workaround section](https://github.com/pop123123123/CLI_sentence_mixing#restrictions-and-workarounds) of the CLI dedicated github page.  
If you cannot find your answer there, please open an issue on the [CLI application github issues form](https://github.com/pop123123123/CLI_sentence_mixing/issues).  
We will be happy to help you on it.

Don't hesitate to give us a feedback.

**Comment by nbusser** [comment]
### Conclusion

The problem of @MiClobiMC was that the words in his dictionary were not in upper case, which is mandatory.  
In addition, MFA did not detect non-ASCII unrecognized phonemes symbols. Thus, if MFA produces no error when analyzing the videos, it does not necessary means that the dictionary is valid.

Spanish language have been added to the SM-Dictionaries repository on [this commit](https://github.com/nbusser/SM-Dictionaries/commit/93f7326af0142c93358d59c087e85b76740e8d82).
